In [2]:

import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import somoclu
import pandas as pd

In [4]:
dataset = pd.read_csv('http://sirius.cs.put.poznan.pl/~inf117242/DC.Inputs.csv')
dataset_answ = pd.read_csv('http://sirius.cs.put.poznan.pl/~inf117242/DC.Targets.csv', header=None, names=['Class'])
df_joined = dataset.join(dataset_answ)

In [5]:
df_filtered = df_joined.drop(['custAttr2', 'state1'], axis=1)

In [31]:
df_cut = df_filtered.head(100)
df_cut_train = df_filtered.iloc[50:100]
#df_cut_train["Class"] = None
print(df_cut_train)

    amount  hour1  zip1         custAttr1  field1  field2  hour2  flag1  \
50   38.85      6   708  1234567890123504       2       1      6      0
51   11.01      6   947  1234567890123505       3       1      6      1
52   12.95      6   947  1234567890123505       3       1      6      1
53   38.85      6   303  1234567890123506       3       1      6      1
54   12.95      6   770  1234567890123507       3       0      6      1
55   38.85      7    91  1234567890123508       3       0      7      0
56   49.95      7   378  1234567890123509       3       1      7      0
57   59.40      7   100  1234567890123510       3       0      7      0
58   12.95      7   330  1234567890123511       0       0      7      1
59   10.36      7    21  1234567890123512       2       0      7      1
60   38.85      7   207  1234567890123513       3       1      7      0
61   38.85      7   963  1234567890123514       3       0      7      0
62   12.95      7    91  1234567890123508       3       0      7      0
63   10.36      7   334  1234567890123515       3       1      7      1
64   38.85      7   207  1234567890123516       2       1      7      1
65   38.85      7   224  1234567890123517       1       1      7      0
66   38.85      7   300  1234567890123518       3       0      7      1
67   38.85      7   701  1234567890123519       3       0      7      0
68   42.46      7    87  1234567890123520       3       0      7      0
69   49.95      7   114  1234567890123521       2       0      7      0
70   12.95      7   300  1234567890123522       3       0      7      1
71   25.90      7   833  1234567890123523       0       0      7      0
72   25.90      7   207  1234567890123513       3       1      7      0
73   25.90      7   342  1234567890123524       0       0      7      1
74   38.85      7   454  1234567890123525       3       1      7      1
75   10.36      7   201  1234567890123526       3       0      7      1
76   38.85      7   454  1234567890123525       3       0      8      0
77   38.85      8   163  1234567890123527       3       1      8      0
78   38.85      8    89  1234567890123528       3       1      8      0
79   49.95      8   300  1234567890123529       0       0      8      0
80   10.36      8   700  1234567890123530       1       0      8      1
81   38.85      8   303  1234567890123531       2       0      8      1
82   38.85      8   322  1234567890123532       2       0      8      1
83   38.85      8   327  1234567890123533       0       1      8      1
84   38.85      8   217  1234567890123534       3       1      8      0
85   38.85      8    76  1234567890123535       2       1      8      0
86   12.95      8   281  1234567890123536       0       0      8      1
87   12.95      8   773  1234567890123537       3       1      8      0
88   38.85      8   923  1234567890123538       3       0      8      1
89   38.85      8   701  1234567890123539       2       0      8      0
90   12.95      8   299  1234567890123540       3       0      8      1
91   12.95      8   299  1234567890123540       3       0      8      1
92   31.08      8   363  1234567890123541       2       0      8      1
93   31.08      8   309  1234567890123542       2       0      8      0
94   38.85      8   278  1234567890123543       3       1      8      0
95   38.85      8   482  1234567890123544       3       0      8      0
96   12.95      8   125  1234567890123545       2       0      8      0
97   10.36      8   302  1234567890123546       3       1      8      1
98   38.85      8   532  1234567890123547       2       1      8      0
99   12.95      8   925  1234567890123548       2       0      8      1

    total  field3  field4  indicator1  indicator2  flag2  flag3  flag4  flag5  \
50  38.85    2682      26           0           0      0      0      0      1
51  11.01    -415       7           0           0      1      1      0      4
52  12.95    -415       7           0           0      1      1      0      4
53  38.85    4893       7           0           0      1      1      0      4
54  12.95    3876       6           1           0      0      1      0      2
55  38.85    5775      32           0           0      1      1      0      1
56  49.95   -5894      17           0           0      1      0      0      1
57  59.40    4157      23           0           0      1      1      0      1
58  12.95   -2152       9           1           0      1      0      0      1
59  10.36    3213       8           0           0      1      1      0      1
60  38.85    2116      22           0           0      1      1      0      1
61  38.85    1595      29           0           0      0      0      0      1
62  12.95    5775      32           0           0      1      1      0      1
63  10.36     922      10           0           0      1      1      0      1
64  38.85      27       9           0           0      0      0      0      1
65  38.85   -5681       6           0           0      1      1      0      1
66  38.85    -301      22           0           0      1      1      0      1
67  38.85     469      17           0           0      1      1      0      1
68  42.46    1645      13           0           0      1      1      0      1
69  49.95    1567       7           0           0      1      1      0      1
70  12.95     178       9           0           0      0      0      0      1
71  25.90   -1803      29           0           0      0      0      0      1
72  25.90    2116      22           0           0      1      1      0      1
73  25.90    -552       7           0           0      0      0      0      1
74  38.85   -3235      21           0           0      1      1      0      2
75  10.36    -531      20           0           0      1      1      0      1
76  38.85   -3166       8           0           0      1      1      0      2
77  38.85   -2172      26           0           0      1      1      0      1
78  38.85    7090      12           0           0      1      0      0      1
79  49.95    3663      19           0           0      0      0      0      1
80  10.36     886      12           0           0      1      0      0      1
81  38.85    2790      13           0           0      0      0      0      2
82  38.85   -8269       9           0           0      0      1      0      1
83  38.85     530      10           0           0      0      0      0      1
84  38.85   -4332       8           0           0      1      1      0      1
85  38.85   -1278      17           0           0      0      0      0      1
86  12.95   -3572      16           0           0      1      1      0      2
87  12.95   -3075      26           0           0      1      0      0      1
88  38.85    3104       7           0           0      0      0      0      1
89  38.85    2737      27           0           0      0      0      0      1
90  12.95    -905       6           0           0      1      1      0      1
91  12.95    -905       6           0           0      1      1      0      1
92  31.08    1374      20           0           0      1      0      0      1
93  31.08    -321      25           0           0      1      1      0      1
94  38.85    3865      20           0           0      0      1      0      1
95  38.85   -3652      18           0           0      0      1      0      1
96  12.95    2592      19           0           0      0      0      0      1
97  10.36    3733       7           0           0      0      0      0      2
98  38.85     997      17           0           0      1      0      0      1
99  12.95    5938       7           1           0      0      0      0      1

    Class
50      0
51      0
52      0
53      0
54      0
55      0
56      0
57      0
58      0
59      0
60      0
61      0
62      0
63      0
64      0
65      0
66      0
67      0
68      0
69      0
70      0
71      0
72      0
73      0
74      0
75      0
76      0
77      0
78      0
79      0
80      0
81      0
82      0
83      0
84      0
85      0
86      0
87      0
88      0
89      0
90      0
91      0
92      0
93      0
94      0
95      0
96      0
97      0
98      0
99      0

In [46]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler(feature_range = (0, 1))
data = sc.fit_transform(df_cut)
data_train = sc.fit_transform(df_cut_train)

data_train[:, -1] = None
print(data_train)

[[0.58095432 0.         0.72929936 0.         0.66666667 1.
  0.         0.         0.58095432 0.71300215 0.76923077 0.
  0.         0.         0.         0.         0.                nan]
 [0.01325449 0.         0.98301486 0.0234375  1.         1.
  0.         1.         0.01325449 0.51136142 0.03846154 0.
  0.         1.         1.         0.         1.                nan]
 [0.05281403 0.         0.98301486 0.0234375  1.         1.
  0.         1.         0.05281403 0.51136142 0.03846154 0.
  0.         1.         1.         0.         1.                nan]
 [0.58095432 0.         0.29936306 0.04296875 1.         1.
  0.         1.         0.58095432 0.85695683 0.03846154 0.
  0.         1.         1.         0.         1.                nan]
 [0.05281403 0.         0.79511677 0.06640625 1.         0.
  0.         1.         0.05281403 0.79074158 0.         1.
  0.         0.         1.         0.         0.33333333        nan]
 [0.58095432 0.5        0.07430998 0.08984375 1.         0.
  0.5        0.         0.58095432 0.91438245 1.         0.
  0.         1.         1.         0.         0.                nan]
 [0.80730016 0.5        0.37898089 0.11328125 1.         1.
  0.5        0.         0.80730016 0.15463246 0.42307692 0.
  0.         1.         0.         0.         0.                nan]
 [1.         0.5        0.08386412 0.13671875 1.         0.
  0.5        0.         1.         0.80903705 0.65384615 0.
  0.         1.         1.         0.         0.                nan]
 [0.05281403 0.5        0.32802548 0.16015625 0.         0.
  0.5        1.         0.05281403 0.39826812 0.11538462 1.
  0.         1.         0.         0.         0.                nan]
 [0.         0.5        0.         0.1796875  0.66666667 0.
  0.5        1.         0.         0.74757471 0.07692308 0.
  0.         1.         1.         0.         0.                nan]
 [0.58095432 0.5        0.19745223 0.203125   1.         1.
  0.5        0.         0.58095432 0.67615079 0.61538462 0.
  0.         1.         1.         0.         0.                nan]
 [0.58095432 0.5        1.         0.2265625  1.         0.
  0.5        0.         0.58095432 0.64222931 0.88461538 0.
  0.         0.         0.         0.         0.                nan]
 [0.05281403 0.5        0.07430998 0.08984375 1.         0.
  0.5        0.         0.05281403 0.91438245 1.         0.
  0.         1.         1.         0.         0.                nan]
 [0.         0.5        0.33227176 0.25       1.         1.
  0.5        1.         0.         0.59841135 0.15384615 0.
  0.         1.         1.         0.         0.                nan]
 [0.58095432 0.5        0.19745223 0.2734375  0.66666667 1.
  0.5        1.         0.58095432 0.54013933 0.11538462 0.
  0.         0.         0.         0.         0.                nan]
 [0.58095432 0.5        0.21549894 0.29296875 0.33333333 1.
  0.5        0.         0.58095432 0.16850055 0.         0.
  0.         1.         1.         0.         0.                nan]
 [0.58095432 0.5        0.29617834 0.31640625 1.         0.
  0.5        1.         0.58095432 0.51878377 0.61538462 0.
  0.         1.         1.         0.         0.                nan]
 [0.58095432 0.5        0.72186837 0.33984375 1.         0.
  0.5        0.         0.58095432 0.56891725 0.42307692 0.
  0.         1.         1.         0.         0.                nan]
 [0.6545677  0.5        0.07006369 0.36328125 1.         0.
  0.5        0.         0.6545677  0.64548473 0.26923077 0.
  0.         1.         1.         0.         0.                nan]
 [0.80730016 0.5        0.09872611 0.38671875 0.66666667 0.
  0.5        0.         0.80730016 0.64040628 0.03846154 0.
  0.         1.         1.         0.         0.                nan]
 [0.05281403 0.5        0.29617834 0.41015625 1.         0.
  0.5        1.         0.05281403 0.5499707  0.11538462 0.
  0.         0.         0.         0.         0.                nan]
 [0.31688418 0.5        0.86199575 0.4296875  0.         0.
  0.5        0.         0.31688418 0.42099095 0.88461538 0.
  0.         0.         0.         0.         0.                nan]
 [0.31688418 0.5        0.19745223 0.203125   1.         1.
  0.5        0.         0.31688418 0.67615079 0.61538462 0.
  0.         1.         1.         0.         0.                nan]
 [0.31688418 0.5        0.34076433 0.453125   0.         0.
  0.5        1.         0.31688418 0.50244157 0.03846154 0.
  0.         0.         0.         0.         0.                nan]
 [0.58095432 0.5        0.4596603  0.4765625  1.         1.
  0.5        1.         0.58095432 0.32775571 0.57692308 0.
  0.         1.         1.         0.         0.33333333        nan]
 [0.         0.5        0.1910828  0.5        1.         0.
  0.5        1.         0.         0.50380884 0.53846154 0.
  0.         1.         1.         0.         0.                nan]
 [0.58095432 0.5        0.4596603  0.4765625  1.         0.
  1.         0.         0.58095432 0.33224819 0.07692308 0.
  0.         1.         1.         0.         0.33333333        nan]
 [0.58095432 1.         0.1507431  0.5234375  1.         1.
  1.         0.         0.58095432 0.39696595 0.76923077 0.
  0.         1.         1.         0.         0.                nan]
 [0.58095432 1.         0.07218684 0.54296875 1.         1.
  1.         0.         0.58095432 1.         0.23076923 0.
  0.         1.         0.         0.         0.                nan]
 [0.80730016 1.         0.29617834 0.56640625 0.         0.
  1.         0.         0.80730016 0.77687349 0.5        0.
  0.         0.         0.         0.         0.                nan]
 [0.         1.         0.72080679 0.58984375 0.33333333 0.
  1.         1.         0.         0.59606745 0.23076923 0.
  0.         1.         0.         0.         0.                nan]
 [0.58095432 1.         0.29936306 0.61328125 0.66666667 0.
  1.         1.         0.58095432 0.72003386 0.26923077 0.
  0.         0.         0.         0.         0.33333333        nan]
 [0.58095432 1.         0.31953291 0.63671875 0.66666667 0.
  1.         1.         0.58095432 0.         0.11538462 0.
  0.         0.         1.         0.         0.                nan]
 [0.58095432 1.         0.32484076 0.66015625 0.         1.
  1.         1.         0.58095432 0.57288886 0.15384615 0.
  0.         0.         0.         0.         0.                nan]
 [0.58095432 1.         0.20806794 0.6796875  1.         1.
  1.         0.         0.58095432 0.25633179 0.07692308 0.
  0.         1.         1.         0.         0.                nan]
 [0.58095432 1.         0.05838641 0.703125   0.66666667 1.
  1.         0.         0.58095432 0.45517286 0.42307692 0.
  0.         0.         0.         0.         0.                nan]
 [0.05281403 1.         0.27600849 0.7265625  0.         0.
  1.         1.         0.05281403 0.30581418 0.38461538 0.
  0.         1.         1.         0.         0.33333333        nan]
 [0.05281403 1.         0.79830149 0.75       1.         1.
  1.         0.         0.05281403 0.33817306 0.76923077 0.
  0.         1.         0.         0.         0.                nan]
 [0.58095432 1.         0.95753715 0.7734375  1.         0.
  1.         1.         0.58095432 0.7404779  0.03846154 0.
  0.         0.         0.         0.         0.                nan]
 [0.58095432 1.         0.72186837 0.79296875 0.66666667 0.
  1.         0.         0.58095432 0.71658311 0.80769231 0.
  0.         0.         0.         0.         0.                nan]
 [0.05281403 1.         0.29511677 0.81640625 1.         0.
  1.         1.         0.05281403 0.4794583  0.         0.
  0.         1.         1.         0.         0.                nan]
 [0.05281403 1.         0.29511677 0.81640625 1.         0.
  1.         1.         0.05281403 0.4794583  0.         0.
  0.         1.         1.         0.         0.                nan]
 [0.42251223 1.         0.36305732 0.83984375 0.66666667 0.
  1.         1.         0.42251223 0.62784035 0.53846154 0.
  0.         1.         0.         0.         0.                nan]
 [0.42251223 1.         0.30573248 0.86328125 0.66666667 0.
  1.         0.         0.42251223 0.51748161 0.73076923 0.
  0.         1.         1.         0.         0.                nan]
 [0.58095432 1.         0.27282378 0.88671875 1.         1.
  1.         0.         0.58095432 0.79002539 0.53846154 0.
  0.         0.         1.         0.         0.                nan]
 [0.58095432 1.         0.48938429 0.91015625 1.         0.
  1.         0.         0.58095432 0.30060551 0.46153846 0.
  0.         0.         1.         0.         0.                nan]
 [0.05281403 1.         0.1104034  0.9296875  0.66666667 0.
  1.         0.         0.05281403 0.70714239 0.5        0.
  0.         0.         0.         0.         0.                nan]
 [0.         1.         0.29830149 0.953125   1.         1.
  1.         1.         0.         0.78143108 0.03846154 0.
  0.         0.         0.         0.         0.33333333        nan]
 [0.58095432 1.         0.54246285 0.9765625  0.66666667 1.
  1.         0.         0.58095432 0.60329449 0.42307692 0.
  0.         1.         0.         0.         0.                nan]
 [0.05281403 1.         0.9596603  1.         0.66666667 0.
  1.         1.         0.05281403 0.92499512 0.03846154 1.
  0.         0.         0.         0.         0.                nan]]

In [8]:
df_joined.groupby(['custAttr1'])['Class'].agg(['sum', 'count']).sort_values('count', ascending=False)

# for count also consider 'size'. size will return n for NaN values also, whereas 'count' will not.

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>sum</th>
      <th>count</th>
    </tr>
    <tr>
      <th>custAttr1</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>1234567890124236</th>
      <td>0</td>
      <td>68</td>
    </tr>
    <tr>
      <th>1234567890139015</th>
      <td>49</td>
      <td>63</td>
    </tr>
    <tr>
      <th>1234567890124580</th>
      <td>0</td>
      <td>57</td>
    </tr>
    <tr>
      <th>1234567890125395</th>
      <td>0</td>
      <td>50</td>
    </tr>
    <tr>
      <th>1234567890141164</th>
      <td>0</td>
      <td>46</td>
    </tr>
    <tr>
      <th>1234567890162274</th>
      <td>0</td>
      <td>44</td>
    </tr>
    <tr>
      <th>1234567890128594</th>
      <td>0</td>
      <td>39</td>
    </tr>
    <tr>
      <th>1234567890123922</th>
      <td>0</td>
      <td>34</td>
    </tr>
    <tr>
      <th>1234567890158597</th>
      <td>0</td>
      <td>32</td>
    </tr>
    <tr>
      <th>1234567890124577</th>
      <td>0</td>
      <td>32</td>
    </tr>
    <tr>
      <th>1234567890140678</th>
      <td>0</td>
      <td>32</td>
    </tr>
    <tr>
      <th>1234567890149982</th>
      <td>19</td>
      <td>28</td>
    </tr>
    <tr>
      <th>1234567890123978</th>
      <td>0</td>
      <td>27</td>
    </tr>
    <tr>
      <th>1234567890127943</th>
      <td>0</td>
      <td>24</td>
    </tr>
    <tr>
      <th>1234567890124248</th>
      <td>0</td>
      <td>24</td>
    </tr>
    <tr>
      <th>1234567890132303</th>
      <td>0</td>
      <td>23</td>
    </tr>
    <tr>
      <th>1234567890136457</th>
      <td>0</td>
      <td>22</td>
    </tr>
    <tr>
      <th>1234567890123772</th>
      <td>0</td>
      <td>22</td>
    </tr>
    <tr>
      <th>1234567890132448</th>
      <td>0</td>
      <td>22</td>
    </tr>
    <tr>
      <th>1234567890156738</th>
      <td>0</td>
      <td>21</td>
    </tr>
    <tr>
      <th>1234567890148517</th>
      <td>0</td>
      <td>21</td>
    </tr>
    <tr>
      <th>1234567890124102</th>
      <td>0</td>
      <td>21</td>
    </tr>
    <tr>
      <th>1234567890131824</th>
      <td>0</td>
      <td>21</td>
    </tr>
    <tr>
      <th>1234567890125390</th>
      <td>0</td>
      <td>21</td>
    </tr>
    <tr>
      <th>1234567890125940</th>
      <td>18</td>
      <td>21</td>
    </tr>
    <tr>
      <th>1234567890126990</th>
      <td>0</td>
      <td>21</td>
    </tr>
    <tr>
      <th>1234567890126042</th>
      <td>0</td>
      <td>20</td>
    </tr>
    <tr>
      <th>1234567890151792</th>
      <td>0</td>
      <td>20</td>
    </tr>
    <tr>
      <th>1234567890129496</th>
      <td>0</td>
      <td>20</td>
    </tr>
    <tr>
      <th>1234567890123912</th>
      <td>0</td>
      <td>20</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>1234567890151716</th>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>1234567890151754</th>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>1234567890151717</th>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>1234567890151718</th>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>1234567890151719</th>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>1234567890151720</th>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>1234567890151721</th>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>1234567890151722</th>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>1234567890151724</th>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>1234567890151725</th>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>1234567890151726</th>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>1234567890151727</th>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>1234567890151728</th>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>1234567890151729</th>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>1234567890151730</th>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>1234567890151731</th>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>1234567890151734</th>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>1234567890151735</th>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>1234567890151736</th>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>1234567890151737</th>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>1234567890151739</th>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>1234567890151742</th>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>1234567890151743</th>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>1234567890151744</th>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>1234567890151745</th>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>1234567890151748</th>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>1234567890151749</th>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>1234567890151751</th>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>1234567890151753</th>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>1234567890197184</th>
      <td>0</td>
      <td>1</td>
    </tr>
  </tbody>
</table>
<p>73729 rows × 2 columns</p>
</div>

In [12]:
#!pip install pomegranate
from pomegranate import *
import numpy

#X = numpy.load('data.npy')
model = BayesianNetwork.from_samples(df_cut,algorithm='greedy')

In [18]:
# Defining the Bayesian Model

from pgmpy.models import BayesianModel
from pgmpy.estimators import MaximumLikelihoodEstimator, BayesianEstimator

model = BayesianModel()
model.add_node('Class')

# Fitting the data to the model using Maximum Likelihood Estimator
model.fit(df_cut[1:70], estimator=MaximumLikelihoodEstimator)
print(model)

In [51]:
from pomegranate import *
import numpy

print(data)
model = BayesianNetwork.from_samples(data[1:70],
                algorithm='chow-liu', verbose=True)

[[0.05281403 0.         1.         ... 0.         0.         0.        ]
 [0.58095432 0.         0.99385246 ... 0.         0.         0.        ]
 [0.58095432 0.         0.40163934 ... 0.         0.         0.        ]
 ...
 [0.         1.         0.29918033 ... 0.         0.33333333 0.        ]
 [0.58095432 1.         0.53483607 ... 0.         0.         0.        ]
 [0.05281403 1.         0.9375     ... 0.         0.         0.        ]]

TypeError: from_samples() got an unexpected keyword argument 'verbose'

In [49]:
x = model.predict(data_train)

ValueError: State '2' does not have key '0.7292993630573248'